### ISSUE TITLE
package actor and client 

### ISSUE THREAD

**Issue by thuvh** [VirtualCable/openuds#101]
Hi, is there any simple guilde to package (deb, rpm, exe) for actor and client?

**Comment by dkmstr** [comment]
Sorry, not a "written document" to guide you, but you have this script:

https://github.com/VirtualCable/openuds/blob/v3.6/client-py3/full/linux/build-packages.sh

That may be used as "guide".. I recommend you to create the packages from a Debian/ubuntu, (i currently create them from debian 12).

Hope this helps

**Comment by thuvh** [comment]
Yep, I can build linux succesfully from this script. Is there any recommenation for building window and mac application?
