### ISSUE TITLE
Metapool v3.6 not working

### ISSUE THREAD

**Issue by thuocnq055** [VirtualCable/openuds#106]
Hello!
Version 3.6 i see openuds\server\src\uds\core\managers\user_service.py line 1006 and 1009
 p[1].usage() is tuple can't compare with 100

**Comment by dkmstr** [comment]
Effectively, it was a bug.
Fixed on https://github.com/VirtualCable/openuds/commit/78a70368b762b64812b557ae1bace32384cd585d

Thank you very much.

**Comment by dkmstr** [comment]
https://github.com/VirtualCable/openuds-gui

**Comment by thuocnq055** [comment]
thank you so much

**Comment by thuocnq055** [comment]
@dkmstr can you share for me source code openuds-gui/tree/v3.6/src/server ?. i really need it

**Comment by dkmstr** [comment]
"server" has no source code, are a couple of testing files, not needed for anything but for tests (referenced on index.html). No server code, never has been a server code (they are directly created by uds broker, with the related methods).

All the source code for the user interface part is inside the project.

Hope this helps

Note: anything missing in there, is provided by UDS, as those files...

**Comment by thuocnq055** [comment]
@dkmstr tks for help.
