### ISSUE TITLE
The download link for virt-viewer is not working.

### ISSUE THREAD

**Issue by VelociraptorNikita** [VirtualCable/openuds#114]
The download link for virt-viewer is not working.
In the lines https://github.com/VirtualCable/openuds/blob/v3.6/server/src/uds/transports/SPICE/scripts/windows/direct.py#L28C14-L28C47 and https://github.com/ VirtualCable/openuds/blob/v3.6/server/src/uds/transports/SPICE/scripts/windows/tunnel.py#L29 the “/” sign must be removed from the link.
<a href="http://virt-manager.org/download/">Open download page</a> -> <a href="http://virt-manager.org/download">Open download page< /a>
![Screenshot 2024-05-29 153408](https://github.com/VirtualCable/openuds/assets/40734832/4dcc9785-7595-4780-932a-66d076663ae1)

**Comment by dkmstr** [comment]
Fixed... ;-)
Thanks
