### ISSUE TITLE
Error on filling openstack pool due new instance dont have mac address

### ISSUE THREAD

**Issue by dafafdafafadfa** [VirtualCable/openuds#116]
master
Exception when fill pool with the opentask live provider. 
In our case instances obtains address in minutes later than vm created.

What is expected way for implements get_unique_id()?
Should we await mac address or can use any unique? i.e. instance uuid?

uds.core.managers.userservice_helpers.opchecker:state_updater 266 Checking service state
Traceback (most recent call last):
  File "/root/openuds/server/src/uds/core/managers/userservice_helpers/opchecker.py", line 240, in state_updater
    userservice.unique_id = userservice_instance.get_unique_id()  # Updates uniqueId
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/openuds/server/src/uds/core/services/generics/dynamic/userservice.py", line 346, in get_unique_id
    self._mac = self.service().get_mac(self, self._vmid) or ''
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/openuds/server/src/uds/services/OpenStack/service.py", line 265, in get_mac
    return self.api.get_server_info(vmid).validated().addresses[0].mac
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
DEBUG 2024-09-24 15:50:00,178 uds.core.managers.userservice:locate_user_service 905 Found service: User service new service pool 2\, unique_id , cache_level 0, user vic@new internal database auth (id:1), name , state Error:In preparation
ERROR 2024-09-24 15:50:00,179 uds.web.util.services:enable_service 470 Error
Traceback (most recent call last):
  File "/root/openuds/server/src/uds/web/util/services.py", line 431, in enable_service
    info = UserServiceManager.manager().get_user_service_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/openuds/server/src/uds/core/managers/userservice.py", line 943, in get_user_service_info
    raise InvalidServiceException(

**Comment by dkmstr** [comment]
Unfortunately, UDS needs the mac of the VM in order to allow to be configured. (In fact, the MAC or the IP, but some network related info that, with the template secret, will allow uds to identify vdi).

The best way is simply wait for the MAC to be present, that is, is very easy to patch UDS to allow "delayed" network interface info, simply patching " File "/root/openuds/server/src/uds/services/OpenStack/service.py", line 265, in get_mac" to check if there are adresses and, if not, return empty string... As long as it has no unique id, should keep in.

If it is something normal in OpenStack (i didn't see it before..), i can adapt the code to wait for the mac to be before assuming it has been created...

**Comment by dafafdafafadfa** [comment]
I think this is typical behavior for openstack. I haven't double-checked how creating a virtual machine looks like via API, but via UI it looks exactly like this.
Perhaps there are additional ways to create virtual machines with pre-allocation of network ports, but this method is quite unusual. Thanks for the answer. I feel quite comfortable in the master branch.

**Comment by dkmstr** [comment]
I have made a change for allowing this.
If i understood, there is no Network until a while after the instance is created, isnt it?

If that is the case, that is, eventually after creating it, it will get a network card and be started correctly, this pull should solve your issues.

https://github.com/VirtualCable/openuds/commit/c04a2b7396b06941722bb402cefe64515e6b69f7

Hope this helps,
