### ISSUE TITLE
Number of services left (Feature request/workaround)

### ISSUE THREAD

**Issue by eibol** [VirtualCable/openuds#119]
Hi,thanks a lot for this awesome project.
I'd like to ask if it there is a way to display the number of remaining services in a given pool or meta-pool.

It is good to know, specially because when users try HTML5 transport, there is only a generic error message, unlike when
using RDP, which displays that no more services are available for users.

Thanks!

**Comment by dkmstr** [comment]
Yes, in 4.0 (currently stabilizing it, maybe at end of this month, or next, it reaches the "beta" fase :)), it possible in pools and metapools (especifically in the name), using some "macros", but on 3.6 only on pools:

https://github.com/VirtualCable/openuds/blob/c96193f75576bb32c4f7a55ce376afd9d1be4824/server/src/uds/web/util/services.py#L300

Basically the
```python
        def macro_info(x: str) -> str:
            return (
                x.replace('{use}', use_percent)
                .replace('{total}', max_srvs)
                .replace('{usec}', use_count)
                .replace('{left}', left_count)
            )
``` 

The "{}" "macros" are replaced on pools on the name and the visual name.

So, if you have a pool that reads "Sample Pool {usec} used, {left} available.", you have 32 used and 8 left, the web will show "Sample pool 32 used, 8 available"

The 3.6 does not supports this on Metapools. Hope this helps :)

**Comment by eibol** [comment]
Great thanks, I'll try it. If necessary, I could split metapool.

**Comment by dkmstr** [comment]
In no time, you probably could use 4.0, that have all these features, and much better implemented :)

**Comment by eibol** [comment]
> In no time, you probably could use 4.0, that have all these features, and much better implemented :)

I'm looking forward to it.

For some reason, only  {use} and {usec} worked in visual_name, but that's more than enough. Thanks again
