### ISSUE TITLE
Simultaneous ssh connections to a virtual desktop

### ISSUE THREAD

**Issue by eibol** [VirtualCable/openuds#121]
Hi, not actually an issue. I was wondering if there is a possibility for more than one user to connect to a remote computer/desktop using SSH transport, or any other. 

As fas as I have checked, every service is assigned in a user/ip pair, so two users can't be assigned the same IP address.
Thank a lot!

**Comment by dkmstr** [comment]
Currently, there is only one "N-to-1" connections possible, and is on PhysicalMachines "single ip". That is, you can configure a single machine as a service, and give as many users as you like access to it.

This shoulf solve your problem. If you have many machines, simply create as many services (and associated pools) as you need.

Regards!
