### ISSUE TITLE
Enable floatbar for FreeRDP

### ISSUE THREAD

**Issue by TristanWasTaken** [VirtualCable/openuds#122]
Exiting the rdp application on Linux is a pain.
While the floatbar is enabled on Windows, it seems like it's disabled for Linux.
FreeRDP has a floatbar option which is disabled by default, so it would be cool if it was enabled (`/floatbar on`).
![image](https://github.com/user-attachments/assets/4e1e82de-0ed8-476b-a982-c8a86e0290c2)

**Comment by dkmstr** [comment]
Actually you can enable it on Linux on this:
![imagen](https://github.com/user-attachments/assets/24a11c3a-2140-47d3-9711-5d9395f2388e)

But you are right, it's much better yo have a common floatbar without needeing to add the parameters manually on the section :)

I'm going to "honor" the settings on the Display tab, without needing to add manually the parameter. But this is going to be available on 4.0. Meanwhile, you can add manually the parameter ;-)

**Comment by dkmstr** [comment]
Done, added on 3d57cb9bec3dc28f5a8d86d3e0f30d03afaf8a66

Thanks for the suggestion!! ;-)
