### ISSUE TITLE
Xen-NG Server

### ISSUE THREAD

**Issue by Usa4** [VirtualCable/openuds#79]
Hi, I have a trial version of uds enterprise and also installed openuds version 3.0, I have such a problem, I was able to publish the OS on the enterprise version and everything is fine, but unfortunately on the openuds version I have a status of waiting publication, I don’t know what not like this:( (Xen-server version 8.2)

**Comment by Usa4** [comment]
Is it possible that this has something to do with the "paramiko" package?

**Comment by Usa4** [comment]
Paramiko requires Cryptography version higher than 3.3 to work, but on versions higher than 2.9 nothing starts and it is impossible to raise the site, maybe some specific version of paramiko is needed, could you still specify the versions of the libraries that are used :)
I will be very grateful, regards

**Comment by severinsm** [comment]
hey, 

I didn't bother to compile it locally,
I've build the uds server in a docker image.

something like:
# base image  
FROM python:3.10
# setup environment variable  
ENV DockerHOME=/home/uds/server  

# set work directory  
RUN mkdir -p $DockerHOME  

# where your code lives  
WORKDIR $DockerHOME  

# set environment variables  
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1  

# install dependencies  
RUN pip install --upgrade pip  
RUN apt update && apt install libsasl2-dev python-dev libldap2-dev libssl-dev -y

# copy whole project to your docker home directory. 
COPY . $DockerHOME  
# run this command to install all dependencies  
RUN pip install -r requirements.txt  
# port where the Django app runs  
EXPOSE 8000
# start server  
CMD python ./src/manage.py runserver '0.0.0.0:8000'

Also I've modified the code a bit, so I can use django 4 (adjusted django.urls to use re_path 
( see https://stackoverflow.com/questions/70319606/importerror-cannot-import-name-url-from-django-conf-urls-after-upgrading-to )

also needed some extra requirements (
Django
bitarray
html5lib
six
dnspython
lxml
ovirt-engine-sdk-python
matplotlib
pyOpenSSL
mysqlclient
python-ldap
paramiko
defusedxml
python-dateutil
requests
WeasyPrint
webencodings
xml-marshaller
pycrypto>=2.6.1
cryptography
pyrad
pyotp
qrcode
)

**Comment by dkmstr** [comment]
Sorry, your problem is that UDS has 2 parts, a frontend (what you are currently running), and a backend (that is needed to "process" everything). take a look at the "manage.py help" and look for the taskManager

Hope this helps.

**Comment by severinsm** [comment]
it's solved at my end, btw you might fix the "not foud" typo in openuds\server\src\uds\management\commands\taskManager.py
python manage.py taskManager --start did the trick for me
