### ISSUE TITLE
correct version

### ISSUE THREAD

**Issue by Usa4** [VirtualCable/openuds#80]
I think I'm asking too many questions :) But could you tell me, if I added localization to the uds/locale/ folder, then where can I activate and add this language for the frontend? And one more question, where can I explicitly specify the version of OpenUDS, because when I try to download the uds client, an HTTP request is created to download a file called UDSClientSetup-3.x.x-DEVEL, of course I just changed the name of the files and that's it, but such a temporary fix doesn't look very nice :)

**Comment by Usa4** [comment]
Y una pregunta más, al eliminar un servicio en el grupo de servicios, el servicio está en un modo de "eliminación" sin fin, ¿cómo solucionarlo?

**Comment by Usa4** [comment]
Is it possible to use https connection for a broker?

**Comment by Usa4** [comment]
I clarified about HTTPS due to the fact that Actor cannot connect, or rather, it does not determine my authorization options, I think it's HTTPS, is it?

**Comment by Usa4** [comment]
Indeed, HTTPS was required for the UDS Actor to work, which I raised using Nginx
`    server {    
        listen 80;
        listen [::]:80;
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name example.com;
     
        ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;  
     
        location /.well-known {
            alias /var/www/example/.well-known;
        }
     
        location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $server_name;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }`
    here is an example of my config for the HTTPS protocol to work correctly, now I'm trying to figure out how to run the golden image of a machine that is already included in the domain

**Comment by dkmstr** [comment]
> I think I'm asking too many questions :) But could you tell me, if I added localization to the uds/locale/ folder, then where can I activate and add this language for the frontend? And one more question, where can I explicitly specify the version of OpenUDS, because when I try to download the uds client, an HTTP request is created to download a file called UDSClientSetup-3.x.x-DEVEL, of course I just changed the name of the files and that's it, but such a temporary fix doesn't look very nice :)

Sorry for the delay.
The languages are configured as any Django standard app (look here: https://docs.djangoproject.com/en/4.2/topics/i18n/), as e shortcut, edit the "setting.py" file to include any required language, but first i recommend you reading about that on the provided URL :).

About the names of the clients, in fact what you do is what it has to be done (change the name in the code) :). Ever version changes, and compiled clients are not included by default. Anyway, you dont have to change EVERY file, yo can do it here: https://github.com/VirtualCable/openuds/blob/master/server/src/uds/core/__init__.py

**Comment by dkmstr** [comment]
About actor, yes, actor uses an needs HTTPS right now, http support has been removed for security issue. To use SSL, you will need a reverse proxy (as with any Django App btw).

About the domain, you can include an already included inside a domain machine using "unmanaged" actor, or registering it by IP. If it is a golden image, you will need to first remove it from domain, make it golden, and then let UDS actor system to include it using windows domain os manager...

Hope it helps

**Comment by Usa4** [comment]
thank you <3
