### ISSUE TITLE
macOS error

### ISSUE THREAD

**Issue by Usa4** [VirtualCable/openuds#87]
Hello, i have macbook pro 2013 high sierra, I installed UDS client 3.5 for Mac, but when I launch it I get an error and two buttons (console and terminate), any ideas? In the console there seems to be something connected with the login attempt, if necessary, I can provide what is there

**Comment by dkmstr** [comment]
Yes, the problem is the version and the libraries used to build the client... :(

Currently, i build the client with Monterrey, and is compatible with monterrey and Ventura at least, but not with older releases... 

Sorry for the inconenience. :(
