### ISSUE TITLE
CSRF token

### ISSUE THREAD

**Issue by Usa4** [VirtualCable/openuds#88]
Creo que estoy haciendo demasiadas preguntas). Intenté implementar UDS3.5 en hosting y obtuve el error "Falta el token CSRF o es incorrecto", aunque este no fue el caso en UDS3.0. No pude encontrar en qué archivo está escrito el código para procesar solicitudes entrantes, ¿puede decirme dónde buscar y qué agregar?

**Comment by Usa4** [comment]
my mistake, I should have cleared my cookies

**Comment by dkmstr** [comment]
:)
