### ISSUE TITLE
Troubles with rdp on Linux client

### ISSUE THREAD

**Issue by Rusqauere** [VirtualCable/openuds#90]
Hello.
While working through udsclient Linux, the picture freezes too much. When working through xfreerdp, the picture almost never freezes. OS is Debian 12. How can I fix this problem?

**Comment by dkmstr** [comment]
The client, in fact, launches the xfreerdp client, but maybe some parameter is not liking your configuration.
Try adding to the transport (Edit it from the UDS Admin dashboard), on linux Client tab, custom parameters this values:

/rfx /gfx:rfx

Hope this helps,

**Comment by Rusqauere** [comment]
It's work for me in attributes Linux client:
/network:auto /gfx-h264:avc444 +gfx-progressive
