### ISSUE TITLE
Install from git  manual proposal ( spanish )

### ISSUE THREAD

**Issue by jonsito** [VirtualCable/openuds#93]
Hi all.
Finally I got it installed in an Ubuntu-20.04 server VM running under Proxmox :-)

Here comes my little howto (Markdown format). In spanish sorry: if you agree contents, after receiving patches and suggestions, i can look for some time to spend in english translation

Hope it will be useful

Juan Antonio
[openuds-instal_es.md](https://github.com/VirtualCable/openuds/files/13164487/openuds-instal_es.md)

**Comment by dkmstr** [comment]
Thank you very much!!!
I'll take a look to it carefully ;-)

regards
