### ISSUE TITLE
When pressing "UDS Client" Only Windows UDS Client is shown

### ISSUE THREAD

**Issue by jonsito** [VirtualCable/openuds#94]
Hi all
( I apologize for using this site a Q&A Forum. But don't know where OpenUDS forum is -or if exists- )

Not sure about what am i doing wrong... Trying to personalize UDS Server.
Most of things works fine, but I'm unable to get all available clients when pressing "UDS Client" button on login page: just only get Windows Client. Attached screenshot comes.
I've downloaded every other Clients and copy'd into /usr/share/openuds/uds/static/clients/ directory, but no luck.

What am I doing wrong? what's the right way to install, register and show all available clients, as second image shows?

Thanks in advance
Juan Antonio Martínez

![Captura de pantalla de 2023-11-09 09-11-47](https://github.com/VirtualCable/openuds/assets/828257/f22b905f-6c69-4494-be69-a36c5d07f39a)
![Captura de pantalla de 2023-11-09 09-10-50](https://github.com/VirtualCable/openuds/assets/828257/6ff360cb-5bd8-41d6-bd14-1339b3e4871d)

**Comment by dkmstr** [comment]
They should appear correctly. What version of OpenUDS are you trying to use?
Look, the "downloadables" are registered here:

https://github.com/VirtualCable/openuds/blob/b21acb75f834d6ffe93d512ded168352aa7bbc9e/server/src/uds/web/util/configjs.py#L213

They are included in the "json" composed for the client (loaded on initial page load), and all should appear correctly.

If you go to the console, you can see the "udsData" variable, and check if clients (named as plugins) are there... Should be.. :)

![imagen](https://github.com/VirtualCable/openuds/assets/7497696/db05a19c-6abf-4b77-81f1-712a19cb7843)


Anyway, do not user "master" version, it's always under heavy changes, and lots of things may be broken.

Hope this helps

**Comment by jonsito** [comment]
I was using version 3.6.0 from AltLinux.
I've just modified configjs.py as you said. Now everything goes as expected.
Thank you very much for your help.

Juan Antonio
