### ISSUE TITLE
Is it possible let the user choose one specific host from pool with PhysicalMachine Service?

### ISSUE THREAD

**Issue by jonsito** [VirtualCable/openuds#95]
Hi all
In our student's lab we have a set of physical machines running Ubuntu 20.04. By mean of OpenUDS's PhysicalMachine Service (MultipleIP) we can remotely access to them. Everything ok.

But in some circumstances is desirable that the student could choose which machine to connect to. Currently the only way to do it is mapping user-to-machine in configuration, but this solution implies a lot of maintenance work and is not enought
 flexible.

Is there a way to let the user to choose which machine in the pool to connect to?. Something  like a textbox under Machine connection icon  as image shows.

Thanks in advance.

![Captura de pantalla de 2023-11-09 10-06-21](https://github.com/VirtualCable/openuds/assets/828257/9ae482d4-1acb-4cd0-bda5-d7971dbe5af4)
Juan Antonio

**Comment by dkmstr** [comment]
If you want to do this, you can always create a "service" for every computer, and show them all. Currently, there is no other way of allowing a user to select a machine from a pool, and, apart of this method, there is no planning for such support.

Note that the problem with this is that the user may access a machine assigned to other user, and that is not desirable also..

Anyway, i'll take this into account for future service management changes.

Sorry for the inconvenience :(
