### ISSUE TITLE
Typos in Notes

### ISSUE THREAD

**Issue by it4joy** [VirtualCable/openuds#96]
Hi, I found the typos in the following sentence:

> OpenUDS has been _splited_ in _serveral_ repositories

Typos are in words in italics (need: 'splitted' & 'several').

**Comment by dkmstr** [comment]
Thank you very much!! Fixing it!! :)

**Comment by dkmstr** [comment]
Done, again thanks. Any help, and even more with documentation, is welcome ;-)
